### ISSUE TITLE
Implementar funcionalidade de salvar a imagem desenhada no localStorage 

### ISSUE THREAD

**Issue by lrfurtado** [siriusvllos/paintbrush#16]
- [x] pesquisar oque é localStorage no javascript e como usalo, explicar bem resumidamente para luciano no whatsapp
- [ ] usar localStorage no console do chrome, para fazer algumas operacoes com arrays, strings, inteiros e tirar schreenshot mandar para luciano
- [ ] quando formos salvar o desenho que informacoes precisamos guardar para recriar o desenho ?
- [ ] propor como podemos alterar a tela do paintbrush para essa funcioanlidade de salvar, eu quero ter uma menira de ver todos os desnehos salvos.
- [ ] que  funcoes teremos que criar para essa funcionalidade ?

**Comment by siriusvllos** [comment]
qual cor ta em cada posicao // como ler cada cor e posicao, como salvar ela
