### ISSUE TITLE
Criar uma git tag chamada v1.0.0 e publica ela no github para o conteudo atual do branch main

### ISSUE THREAD

**Issue by lrfurtado** [siriusvllos/paintbrush#22]
1. pesquisar como criar tags
1. publicar tag no github 
1. criar uma release do github a partir dessa tag
1. colocar nesse issue um screenshot de onde a tag foi criada visualizar no gitk

**Comment by siriusvllos** [comment]
publiquei a tag seguindo essse tutorial: https://git-scm.com/book/pt-br/v2/Fundamentos-de-Git-Criando-Tags e ela foi publicada (segue imagem) 
![WhatsApp Image 2022-09-21 at 14 31 52](https://user-images.githubusercontent.com/98984845/191572274-20e23ea4-f481-4e52-9ffb-e5a39ab34857.jpeg)
ai eu descobri o que era e como usar um release nesse tutorial: https://www.treinaweb.com.br/blog/criando-release-no-github e deu tudo certo (segue imagem)
![f88d525b-2dd0-4a0f-b946-5730f30c5982-_1_](https://user-images.githubusercontent.com/98984845/191573582-a35dc5ea-0a6b-4482-8841-7c215de1abfa.jpg)

@lrfurtado não entendi direito o item 4, mas se for o que eu tô pensando é essa ultima imagem

**Comment by lrfurtado** [comment]
bom demais era exatamente isso que queria
